version: 0.0
os: linux
files:
  - source: docroot
    destination: /usr/share/nginx/docroot
permissions:
  - object: /usr/share/nginx
    pattern: "**"
    owner: root
    group: root
hooks:
  ApplicationStop:
    - location: bin/aws-codedeploy-samples/load-balancing/elb/deregister_from_elb.sh
    - location: bin/stop.sh
  BeforeInstall:
    - location: bin/clean.sh
  ApplicationStart:
    - location: bin/start.sh
    - location: bin/aws-codedeploy-samples/load-balancing/elb/register_with_elb.sh
