version: 0.0
os: linux
files:
  - source: docroot/
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: bin/aws-codedeploy-samples/load-balancing/elb/deregister_from_elb.sh
    - location: bin/stop.sh
  BeforeInstall:
    - location: bin/clean.sh
  ApplicationStart:
    - location: bin/start.sh
    - location: bin/aws-codedeploy-samples/load-balancing/elb/register_with_elb.sh
